
import { CategoryType, Business, NotificationCategory, Notification, Event, TravelerRecommendation, BannerAd, ChatMessage, Community, Flyer, PlaceCategory } from './types';
import { COMMUNITY_COVER_IMAGES, resolveCommunityImageUrl } from './lib/communityCoverImages';
import { getCommunityRegion } from './lib/regions';

const RAW_COMMUNITIES: Community[] = [
  {
    id: 'all',
    name: 'ALL',
    slug: 'all',
    description: 'All Turkish communities in Canada.',
    memberCount: 5000,
    imageUrl: 'https://images.unsplash.com/photo-1517090504586-fde19ea6066f?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'toronto',
    name: 'Toronto',
    slug: 'toronto',
    description: 'Central Toronto community hub for all neighborhoods.',
    memberCount: 1250,
    imageUrl: 'https://images.unsplash.com/photo-1510253401511-370c97800c0f?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'north-york',
    name: 'North York',
    slug: 'north-york',
    description: 'Connect with the vibrant Turkish community in North York.',
    memberCount: 840,
    imageUrl: 'https://images.unsplash.com/photo-1549247413-4315f606a4bc?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'mississauga',
    name: 'Mississauga',
    slug: 'mississauga',
    description: 'Peel Region community and networking hub.',
    memberCount: 980,
    imageUrl: 'https://images.unsplash.com/photo-1551322019-335606d2003c?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'brampton',
    name: 'Brampton',
    slug: 'brampton',
    description: 'Turkish community group in Brampton area.',
    memberCount: 380,
    imageUrl: 'https://images.unsplash.com/photo-1517090504586-fde19ea6066f?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'richmond-hill',
    name: 'Richmond Hill',
    slug: 'richmond-hill',
    description: 'York Region connection for Richmond Hill residents.',
    memberCount: 520,
    imageUrl: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'markham',
    name: 'Markham',
    slug: 'markham',
    description: 'Markham and surrounding York Region community.',
    memberCount: 440,
    imageUrl: 'https://images.unsplash.com/photo-1444723121867-7a241cacace9?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'oakville',
    name: 'Oakville',
    slug: 'oakville',
    description: 'Oakville Turkish network for residents and families.',
    memberCount: 290,
    imageUrl: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'burlington',
    name: 'Burlington',
    slug: 'burlington',
    description: 'Burlington area community hub.',
    memberCount: 260,
    imageUrl: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'hamilton',
    name: 'Hamilton',
    slug: 'hamilton',
    description: 'Hamilton and Dundas region Turkish hub.',
    memberCount: 410,
    imageUrl: 'https://images.unsplash.com/photo-1447933630983-ca4467f56bc9?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'vaughan',
    name: 'Vaughan',
    slug: 'vaughan',
    description: 'Vaughan and Woodbridge connection.',
    memberCount: 310,
    imageUrl: 'https://images.unsplash.com/photo-1516738901171-8eb4fc13bd20?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'aurora',
    name: 'Aurora',
    slug: 'aurora',
    description: 'Aurora Turkish community in York Region.',
    memberCount: 220,
    imageUrl: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'oshawa',
    name: 'Oshawa',
    slug: 'oshawa',
    description: 'Durham Region connection for Oshawa residents.',
    memberCount: 190,
    imageUrl: 'https://images.unsplash.com/photo-1441260037373-ca546f393843?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'london',
    name: 'London',
    slug: 'london-on',
    description: 'London Ontario community for news and events.',
    memberCount: 340,
    imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'niagara',
    name: 'Niagara Falls',
    slug: 'niagara',
    description: 'Niagara Region Turkish residents group.',
    memberCount: 210,
    imageUrl: 'https://images.unsplash.com/photo-1490682143124-b7327386962b?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'guelph',
    name: 'Guelph',
    slug: 'guelph',
    description: 'Guelph and surrounding area network.',
    memberCount: 150,
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'barrie',
    name: 'Barrie',
    slug: 'barrie',
    description: 'Barrie and Simcoe County connection.',
    memberCount: 180,
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'waterloo',
    name: 'Waterloo',
    slug: 'waterloo',
    description: 'Waterloo city Turkish community hub.',
    memberCount: 310,
    imageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'king',
    name: 'King',
    slug: 'king',
    description: 'King Township Turkish community in York Region.',
    memberCount: 140,
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'stouffville',
    name: 'Stouffville',
    slug: 'stouffville',
    description: 'Whitchurch-Stouffville area Turkish network.',
    memberCount: 165,
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'newmarket',
    name: 'Newmarket',
    slug: 'newmarket',
    description: 'Newmarket Turkish community in York Region.',
    memberCount: 230,
    imageUrl: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'ajax',
    name: 'Ajax',
    slug: 'ajax',
    description: 'Ajax Durham Region Turkish community hub.',
    memberCount: 195,
    imageUrl: 'https://images.unsplash.com/photo-1441260037373-ca546f393843?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'pickering',
    name: 'Pickering',
    slug: 'pickering',
    description: 'Pickering area Turkish residents group.',
    memberCount: 210,
    imageUrl: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'whitby',
    name: 'Whitby',
    slug: 'whitby',
    description: 'Whitby Durham Region Turkish community.',
    memberCount: 185,
    imageUrl: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'kitchener',
    name: 'Kitchener',
    slug: 'kitchener',
    description: 'Kitchener Turkish community in Waterloo Region.',
    memberCount: 275,
    imageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'cambridge',
    name: 'Cambridge',
    slug: 'cambridge',
    description: 'Cambridge area Turkish network and events.',
    memberCount: 200,
    imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'brantford',
    name: 'Brantford',
    slug: 'brantford',
    description: 'Brantford Turkish community connection.',
    memberCount: 155,
    imageUrl: 'https://images.unsplash.com/photo-1447933630983-ca4467f56bc9?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'st-catharines',
    name: 'St. Catharines',
    slug: 'st-catharines',
    description: 'St. Catharines Niagara Region Turkish hub.',
    memberCount: 240,
    imageUrl: 'https://images.unsplash.com/photo-1490682143124-b7327386962b?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'milton',
    name: 'Milton',
    slug: 'milton',
    description: 'Milton Halton Region Turkish community.',
    memberCount: 220,
    imageUrl: 'https://images.unsplash.com/photo-1551322019-335606d2003c?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'caledon',
    name: 'Caledon',
    slug: 'caledon',
    description: 'Caledon Peel Region Turkish residents group.',
    memberCount: 130,
    imageUrl: 'https://images.unsplash.com/photo-1503424886307-b090341d25d1?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'peterborough',
    name: 'Peterborough',
    slug: 'peterborough',
    description: 'Peterborough area Turkish community hub.',
    memberCount: 145,
    imageUrl: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'dufferin-county',
    name: 'Dufferin County',
    slug: 'dufferin-county',
    description: 'Dufferin County Turkish community network.',
    memberCount: 120,
    imageUrl: 'https://images.unsplash.com/photo-1517090504586-fde19ea6066f?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'georgina',
    name: 'Georgina',
    slug: 'georgina',
    description: 'Georgina Lake Simcoe Turkish community.',
    memberCount: 135,
    imageUrl: 'https://images.unsplash.com/photo-1444723121867-7a241cacace9?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'east-gwillimbury',
    name: 'East Gwillimbury',
    slug: 'east-gwillimbury',
    description: 'East Gwillimbury York Region Turkish network.',
    memberCount: 125,
    imageUrl: 'https://images.unsplash.com/photo-1516738901171-8eb4fc13bd20?auto=format&fit=crop&w=400&q=80',
    region: 'ON',
  },
  {
    id: 'ottawa',
    name: 'Ottawa',
    slug: 'ottawa',
    description: 'National Capital Region Turkish community hub — Ottawa & Outaouais.',
    memberCount: 520,
    imageUrl: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=800&q=80',
    region: 'QC',
  },
  {
    id: 'montreal',
    name: 'Montreal',
    slug: 'montreal',
    description: 'Montreal Turkish community hub for the greater metro area.',
    memberCount: 980,
    imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80',
    region: 'QC',
  },
  {
    id: 'laval',
    name: 'Laval',
    slug: 'laval',
    description: 'Laval Turkish residents and business network.',
    memberCount: 420,
    imageUrl: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=800&q=80',
    region: 'QC',
  },
  {
    id: 'quebec-city',
    name: 'Quebec City',
    slug: 'quebec-city',
    description: 'Quebec City Turkish community for culture and events.',
    memberCount: 310,
    imageUrl: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=800&q=80',
    region: 'QC',
  },
  {
    id: 'gatineau',
    name: 'Gatineau',
    slug: 'gatineau',
    description: 'Outaouais region Turkish community in Gatineau.',
    memberCount: 280,
    imageUrl: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&w=800&q=80',
    region: 'QC',
  },
  {
    id: 'longueuil',
    name: 'Longueuil',
    slug: 'longueuil',
    description: 'South Shore Montreal Turkish community hub.',
    memberCount: 350,
    imageUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=800&q=80',
    region: 'QC',
  },
  {
    id: 'sherbrooke',
    name: 'Sherbrooke',
    slug: 'sherbrooke',
    description: 'Estrie region Turkish community in Sherbrooke.',
    memberCount: 190,
    imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80',
    region: 'QC',
  },
  {
    id: 'levis',
    name: 'Lévis',
    slug: 'levis',
    description: 'Lévis and south shore Quebec City Turkish network.',
    memberCount: 170,
    imageUrl: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=800&q=80',
    region: 'QC',
  },
  {
    id: 'trois-rivieres',
    name: 'Trois-Rivières',
    slug: 'trois-rivieres',
    description: 'Mauricie region Turkish community hub.',
    memberCount: 140,
    imageUrl: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&w=800&q=80',
    region: 'QC',
  },
  {
    id: 'brossard',
    name: 'Brossard',
    slug: 'brossard',
    description: 'Brossard South Shore Turkish residents network.',
    memberCount: 260,
    imageUrl: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=800&q=80',
    region: 'QC',
  },
  {
    id: 'terrebonne',
    name: 'Terrebonne',
    slug: 'terrebonne',
    description: 'North Shore Montreal Turkish community in Terrebonne.',
    memberCount: 220,
    imageUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=800&q=80',
    region: 'QC',
  },
  {
    id: 'calgary',
    name: 'Calgary',
    slug: 'calgary',
    description: 'Calgary Turkish community hub for southern Alberta.',
    memberCount: 640,
    imageUrl: 'https://images.unsplash.com/photo-1518105779582-896276082c75?auto=format&fit=crop&w=800&q=80',
    region: 'AB',
  },
  {
    id: 'edmonton',
    name: 'Edmonton',
    slug: 'edmonton',
    description: 'Capital region Turkish community in Edmonton.',
    memberCount: 520,
    imageUrl: 'https://images.unsplash.com/photo-1595278069441-2cf295f1b1be?auto=format&fit=crop&w=800&q=80',
    region: 'AB',
  },
  {
    id: 'red-deer',
    name: 'Red Deer',
    slug: 'red-deer',
    description: 'Central Alberta Turkish residents network.',
    memberCount: 180,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
    region: 'AB',
  },
  {
    id: 'lethbridge',
    name: 'Lethbridge',
    slug: 'lethbridge',
    description: 'Southern Alberta Turkish community in Lethbridge.',
    memberCount: 150,
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
    region: 'AB',
  },
  {
    id: 'medicine-hat',
    name: 'Medicine Hat',
    slug: 'medicine-hat',
    description: 'Medicine Hat Turkish community and business network.',
    memberCount: 120,
    imageUrl: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=800&q=80',
    region: 'AB',
  },
  {
    id: 'fort-mcmurray',
    name: 'Fort McMurray',
    slug: 'fort-mcmurray',
    description: 'Wood Buffalo region Turkish community hub.',
    memberCount: 210,
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80',
    region: 'AB',
  },
  {
    id: 'vancouver',
    name: 'Vancouver',
    slug: 'vancouver',
    description: 'Metro Vancouver Turkish community hub.',
    memberCount: 890,
    imageUrl: 'https://images.unsplash.com/photo-1559511269-83aefeb81370?auto=format&fit=crop&w=800&q=80',
    region: 'BC',
  },
  {
    id: 'surrey',
    name: 'Surrey',
    slug: 'surrey',
    description: 'Surrey and Fraser Valley Turkish community.',
    memberCount: 460,
    imageUrl: 'https://images.unsplash.com/photo-1501594907352-04cda38fbf2d?auto=format&fit=crop&w=800&q=80',
    region: 'BC',
  },
  {
    id: 'burnaby',
    name: 'Burnaby',
    slug: 'burnaby',
    description: 'Burnaby Turkish residents and business network.',
    memberCount: 380,
    imageUrl: 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=80',
    region: 'BC',
  },
  {
    id: 'victoria',
    name: 'Victoria',
    slug: 'victoria',
    description: 'Vancouver Island Turkish community in Victoria.',
    memberCount: 290,
    imageUrl: 'https://images.unsplash.com/photo-1569163139394-de4798aa62b6?auto=format&fit=crop&w=800&q=80',
    region: 'BC',
  },
  {
    id: 'kelowna',
    name: 'Kelowna',
    slug: 'kelowna',
    description: 'Okanagan region Turkish community hub.',
    memberCount: 240,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
    region: 'BC',
  },
  {
    id: 'richmond',
    name: 'Richmond',
    slug: 'richmond',
    description: 'Richmond BC Turkish community network.',
    memberCount: 320,
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=800&q=80',
    region: 'BC',
  },
  {
    id: 'winnipeg',
    name: 'Winnipeg',
    slug: 'winnipeg',
    description: 'Winnipeg Turkish community hub for Manitoba.',
    memberCount: 480,
    imageUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=800&q=80',
    region: 'MB',
  },
  {
    id: 'brandon',
    name: 'Brandon',
    slug: 'brandon',
    description: 'Westman region Turkish community in Brandon.',
    memberCount: 140,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
    region: 'MB',
  },
  {
    id: 'steinbach',
    name: 'Steinbach',
    slug: 'steinbach',
    description: 'Southeast Manitoba Turkish residents network.',
    memberCount: 110,
    imageUrl: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=800&q=80',
    region: 'MB',
  },
  {
    id: 'thompson',
    name: 'Thompson',
    slug: 'thompson',
    description: 'Northern Manitoba Turkish community hub.',
    memberCount: 95,
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80',
    region: 'MB',
  },
  {
    id: 'portage-la-prairie',
    name: 'Portage la Prairie',
    slug: 'portage-la-prairie',
    description: 'Central Plains Turkish community network.',
    memberCount: 85,
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
    region: 'MB',
  },
  {
    id: 'selkirk',
    name: 'Selkirk',
    slug: 'selkirk',
    description: 'Interlake region Turkish community in Selkirk.',
    memberCount: 90,
    imageUrl: 'https://images.unsplash.com/photo-1444723121867-7a241cacace9?auto=format&fit=crop&w=800&q=80',
    region: 'MB',
  },
  {
    id: 'saskatoon',
    name: 'Saskatoon',
    slug: 'saskatoon',
    description: 'Saskatoon Turkish community hub for central Saskatchewan.',
    memberCount: 360,
    imageUrl: 'https://images.unsplash.com/photo-1518105779582-896276082c75?auto=format&fit=crop&w=800&q=80',
    region: 'SK',
  },
  {
    id: 'regina',
    name: 'Regina',
    slug: 'regina',
    description: 'Capital region Turkish community in Regina.',
    memberCount: 320,
    imageUrl: 'https://images.unsplash.com/photo-1595278069441-2cf295f1b1be?auto=format&fit=crop&w=800&q=80',
    region: 'SK',
  },
  {
    id: 'prince-albert',
    name: 'Prince Albert',
    slug: 'prince-albert',
    description: 'Northern Saskatchewan Turkish residents network.',
    memberCount: 120,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
    region: 'SK',
  },
  {
    id: 'moose-jaw',
    name: 'Moose Jaw',
    slug: 'moose-jaw',
    description: 'Southern Saskatchewan Turkish community hub.',
    memberCount: 100,
    imageUrl: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=800&q=80',
    region: 'SK',
  },
  {
    id: 'swift-current',
    name: 'Swift Current',
    slug: 'swift-current',
    description: 'Southwest Saskatchewan Turkish community.',
    memberCount: 85,
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
    region: 'SK',
  },
  {
    id: 'yorkton',
    name: 'Yorkton',
    slug: 'yorkton',
    description: 'East-central Saskatchewan Turkish network.',
    memberCount: 90,
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80',
    region: 'SK',
  },
  {
    id: 'halifax',
    name: 'Halifax',
    slug: 'halifax',
    description: 'Halifax Regional Municipality Turkish community hub.',
    memberCount: 420,
    imageUrl: 'https://images.unsplash.com/photo-1559511269-83aefeb81370?auto=format&fit=crop&w=800&q=80',
    region: 'NS',
  },
  {
    id: 'dartmouth',
    name: 'Dartmouth',
    slug: 'dartmouth',
    description: 'Dartmouth Turkish residents and business network.',
    memberCount: 280,
    imageUrl: 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=80',
    region: 'NS',
  },
  {
    id: 'sydney',
    name: 'Sydney',
    slug: 'sydney',
    description: 'Cape Breton Turkish community in Sydney.',
    memberCount: 150,
    imageUrl: 'https://images.unsplash.com/photo-1569163139394-de4798aa62b6?auto=format&fit=crop&w=800&q=80',
    region: 'NS',
  },
  {
    id: 'truro',
    name: 'Truro',
    slug: 'truro',
    description: 'Central Nova Scotia Turkish community hub.',
    memberCount: 110,
    imageUrl: 'https://images.unsplash.com/photo-1501594907352-04cda38fbf2d?auto=format&fit=crop&w=800&q=80',
    region: 'NS',
  },
  {
    id: 'new-glasgow',
    name: 'New Glasgow',
    slug: 'new-glasgow',
    description: 'Pictou County Turkish community network.',
    memberCount: 95,
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=800&q=80',
    region: 'NS',
  },
  {
    id: 'bridgewater',
    name: 'Bridgewater',
    slug: 'bridgewater',
    description: 'South Shore Nova Scotia Turkish community.',
    memberCount: 100,
    imageUrl: 'https://images.unsplash.com/photo-1444723121867-7a241cacace9?auto=format&fit=crop&w=800&q=80',
    region: 'NS',
  },
  {
    id: 'moncton',
    name: 'Moncton',
    slug: 'moncton',
    description: 'Greater Moncton Turkish community hub.',
    memberCount: 310,
    imageUrl: 'https://images.unsplash.com/photo-1518105779582-896276082c75?auto=format&fit=crop&w=800&q=80',
    region: 'NB',
  },
  {
    id: 'saint-john',
    name: 'Saint John',
    slug: 'saint-john',
    description: 'Saint John Turkish residents and business network.',
    memberCount: 240,
    imageUrl: 'https://images.unsplash.com/photo-1595278069441-2cf295f1b1be?auto=format&fit=crop&w=800&q=80',
    region: 'NB',
  },
  {
    id: 'fredericton',
    name: 'Fredericton',
    slug: 'fredericton',
    description: 'Capital region Turkish community in Fredericton.',
    memberCount: 200,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
    region: 'NB',
  },
  {
    id: 'dieppe',
    name: 'Dieppe',
    slug: 'dieppe',
    description: 'Dieppe Turkish community in the Moncton metro.',
    memberCount: 180,
    imageUrl: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=800&q=80',
    region: 'NB',
  },
  {
    id: 'miramichi',
    name: 'Miramichi',
    slug: 'miramichi',
    description: 'Miramichi region Turkish community network.',
    memberCount: 90,
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
    region: 'NB',
  },
  {
    id: 'edmundston',
    name: 'Edmundston',
    slug: 'edmundston',
    description: 'Madawaska region Turkish community in Edmundston.',
    memberCount: 85,
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80',
    region: 'NB',
  },
  {
    id: 'st-johns',
    name: "St. John's",
    slug: 'st-johns',
    description: "St. John's Turkish community hub for Newfoundland and Labrador.",
    memberCount: 290,
    imageUrl: 'https://images.unsplash.com/photo-1559511269-83aefeb81370?auto=format&fit=crop&w=800&q=80',
    region: 'NL',
  },
  {
    id: 'mount-pearl',
    name: 'Mount Pearl',
    slug: 'mount-pearl',
    description: 'Mount Pearl Turkish residents network.',
    memberCount: 160,
    imageUrl: 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=80',
    region: 'NL',
  },
  {
    id: 'corner-brook',
    name: 'Corner Brook',
    slug: 'corner-brook',
    description: 'Western Newfoundland Turkish community hub.',
    memberCount: 120,
    imageUrl: 'https://images.unsplash.com/photo-1569163139394-de4798aa62b6?auto=format&fit=crop&w=800&q=80',
    region: 'NL',
  },
  {
    id: 'grand-falls-windsor',
    name: 'Grand Falls-Windsor',
    slug: 'grand-falls-windsor',
    description: 'Central Newfoundland Turkish community.',
    memberCount: 100,
    imageUrl: 'https://images.unsplash.com/photo-1501594907352-04cda38fbf2d?auto=format&fit=crop&w=800&q=80',
    region: 'NL',
  },
  {
    id: 'gander',
    name: 'Gander',
    slug: 'gander',
    description: 'Gander region Turkish residents network.',
    memberCount: 85,
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=800&q=80',
    region: 'NL',
  },
  {
    id: 'happy-valley-goose-bay',
    name: 'Happy Valley-Goose Bay',
    slug: 'happy-valley-goose-bay',
    description: 'Labrador Turkish community hub.',
    memberCount: 75,
    imageUrl: 'https://images.unsplash.com/photo-1444723121867-7a241cacace9?auto=format&fit=crop&w=800&q=80',
    region: 'NL',
  },
  {
    id: 'charlottetown',
    name: 'Charlottetown',
    slug: 'charlottetown',
    description: 'Prince Edward Island Turkish community hub.',
    memberCount: 180,
    imageUrl: 'https://images.unsplash.com/photo-1518105779582-896276082c75?auto=format&fit=crop&w=800&q=80',
    region: 'PE',
  },
  {
    id: 'summerside',
    name: 'Summerside',
    slug: 'summerside',
    description: 'Summerside Turkish residents and business network.',
    memberCount: 120,
    imageUrl: 'https://images.unsplash.com/photo-1595278069441-2cf295f1b1be?auto=format&fit=crop&w=800&q=80',
    region: 'PE',
  },
  {
    id: 'stratford-pe',
    name: 'Stratford',
    slug: 'stratford-pe',
    description: 'Stratford PE Turkish community network.',
    memberCount: 95,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
    region: 'PE',
  },
  {
    id: 'cornwall-pe',
    name: 'Cornwall',
    slug: 'cornwall-pe',
    description: 'Cornwall PE Turkish community.',
    memberCount: 80,
    imageUrl: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=800&q=80',
    region: 'PE',
  },
  {
    id: 'montague',
    name: 'Montague',
    slug: 'montague',
    description: 'Eastern PEI Turkish community hub.',
    memberCount: 70,
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
    region: 'PE',
  },
  {
    id: 'kensington',
    name: 'Kensington',
    slug: 'kensington',
    description: 'Kensington PE Turkish residents network.',
    memberCount: 65,
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80',
    region: 'PE',
  },
];

export function hydrateCommunity(community: Community): Community {
  const region = getCommunityRegion(community);
  return {
    ...community,
    region,
    imageUrl: resolveCommunityImageUrl(community.id, community.imageUrl),
  };
}

export const INITIAL_COMMUNITIES: Community[] = RAW_COMMUNITIES.map(hydrateCommunity);

/** Merge live Firestore communities with local seed so QC cities always appear. */
export function mergeCommunitiesWithSeed(live: Community[]): Community[] {
  const byId = new Map<string, Community>();
  INITIAL_COMMUNITIES.forEach((community) => {
    byId.set(community.id, hydrateCommunity(community));
  });
  live.forEach((community) => {
    const seed = byId.get(community.id);
    byId.set(
      community.id,
      hydrateCommunity({
        ...(seed || {}),
        ...community,
        id: community.id,
        name: community.name || seed?.name || community.id,
        slug: community.slug || seed?.slug || community.id,
        description: community.description || seed?.description || '',
        memberCount: community.memberCount ?? seed?.memberCount ?? 0,
        region: community.region || seed?.region,
        imageUrl: seed?.imageUrl || community.imageUrl,
      }),
    );
  });
  return Array.from(byId.values());
}

export const INITIAL_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'm1',
    senderId: 'admin_1',
    senderName: 'Admin',
    senderRole: 'admin',
    content: 'Hello! How can I help you today?',
    timestamp: Date.now() - 3600000
  },
  {
    id: 'm2',
    senderId: 'u1',
    senderName: 'Mehmet',
    senderRole: 'user',
    content: 'Hello, I want to list my company but I have some questions about the categories.',
    timestamp: Date.now() - 1800000
  }
];

export const INITIAL_BUSINESSES: Business[] = [
  // --- RESTAURANTS ---
  {
    id: '1',
    name: 'Anatolia Restaurant',
    category: CategoryType.FOOD_DRINK,
    address: '5112 Dundas St W, Etobicoke, ON M9A 1C2',
    phone: '(416) 231-1187',
    description: 'Traditional Turkish cuisine in a warm, low-key setting with kilims and patterned tiles.',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    reviews: [],
    viewCount: 1250,
    verified: true,
    addedBy: 'admin'
  },
  {
    id: 'r2',
    name: 'Pide 21',
    category: CategoryType.FOOD_DRINK,
    address: '1720 Eglinton Ave E, North York, ON M4A 1J7',
    phone: '(416) 759-7433',
    description: 'The best authentic Turkish Pide and Lahmacun experience in Toronto.',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    reviews: [],
    viewCount: 920,
    verified: true,
    addedBy: 'admin'
  },
  {
    id: 'r3',
    name: 'Mustafa Turkish Kitchen',
    category: CategoryType.FOOD_DRINK,
    address: '866 Wilson Ave, North York, ON M3K 1E5',
    phone: '(416) 631-0300',
    description: 'Specializing in wood-fire grilled kebabs and fresh pide.',
    imageUrl: 'https://images.unsplash.com/photo-1544124499-58912cbddaad?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    reviews: [],
    viewCount: 1100,
    verified: true,
    addedBy: 'admin'
  },

  // --- HEALTHCARE ---
  {
    id: '2',
    name: 'Dr. Selin Yilmaz - Family Medicine',
    category: CategoryType.HEALTH,
    address: '123 Medical Dr, North York, ON M2N 5N5',
    phone: '(416) 555-0101',
    description: 'Bilingual family physician dedicated to serving the Turkish-Canadian community.',
    imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71f1e59816?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviews: [],
    viewCount: 840,
    verified: true,
    addedBy: 'admin'
  },

  // --- LEGAL ---
  {
    id: 'l1',
    name: 'Cihan Legal Services',
    category: CategoryType.LAW_IMMIGRATION,
    address: '100 Adelaide St W, Toronto, ON M5H 1S3',
    phone: '(416) 555-2233',
    description: 'Specializing in immigration law, business law, and civil litigation.',
    imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    reviews: [],
    viewCount: 450,
    verified: true,
    addedBy: 'admin'
  },

  // --- GROCERY ---
  {
    id: 'g1',
    name: 'Marche Istanbul',
    category: CategoryType.WHOLESALE,
    address: '3220 Dufferin St, North York, ON M6A 2T3',
    phone: '(416) 782-3555',
    description: 'Your premium source for Turkish groceries, dairy, and freshly baked goods.',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviews: [],
    viewCount: 2200,
    verified: true,
    addedBy: 'admin'
  },
  {
    id: 'g2',
    name: 'Vatan Grocery',
    category: CategoryType.WHOLESALE,
    address: '111 Corporate Dr, Scarborough, ON M1H 3H9',
    phone: '(416) 290-0033',
    description: 'Authentic Turkish products, halva, olives, and premium tea brands.',
    imageUrl: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    reviews: [],
    viewCount: 1500,
    verified: true,
    addedBy: 'admin'
  },

  // --- LOGISTICS ---
  {
    id: 'log1',
    name: 'Maple Leaf Moving & Storage',
    category: CategoryType.LOGISTICS_TRANSPORT,
    address: 'Served: GTA & Beyond',
    phone: '(647) 555-7788',
    description: 'Professional moving services with a dedicated Turkish team. Residential and commercial.',
    imageUrl: 'https://images.unsplash.com/photo-1600518464441-9154a4dea21b?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviews: [],
    viewCount: 680,
    verified: true,
    addedBy: 'admin'
  },

  // --- SERVICES ---
  {
    id: '7',
    name: 'Golden Scissors Barber',
    category: CategoryType.BEAUTY_COSMETICS,
    address: '456 Queen St W, Toronto, ON M5V 2A8',
    phone: '(416) 555-4321',
    description: 'Master Turkish barbers specializing in traditional straight-razor shaves.',
    imageUrl: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    reviews: [],
    viewCount: 310,
    verified: true,
    addedBy: 'admin'
  },
  {
    id: '8',
    name: 'Silk Road Tailors',
    category: CategoryType.TAILOR_DRYCLEAN,
    address: '789 Bloor St W, Toronto, ON M6G 1L6',
    phone: '(416) 555-8899',
    description: 'Expert alterations and custom tailoring with Istanbul heritage.',
    imageUrl: 'https://images.unsplash.com/photo-1520033100230-0370f1a94183?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    reviews: [],
    viewCount: 180,
    verified: true,
    addedBy: 'user'
  },

  // --- REAL ESTATE ---
  {
    id: 're1',
    name: 'Aydin Real Estate Group',
    category: CategoryType.REAL_ESTATE,
    address: 'Mississauga, ON',
    phone: '(905) 555-1234',
    description: 'Helping Turkish families find their dream home in Ontario for over 15 years.',
    imageUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviews: [],
    viewCount: 950,
    verified: true,
    addedBy: 'admin'
  },

  // --- ACCOUNTING ---
  {
    id: 'acc1',
    name: 'Yildiz Tax & Accounting',
    category: CategoryType.ACCOUNTING_FINANCE,
    address: 'Richmond Hill, ON',
    phone: '(416) 555-9900',
    description: 'Personal and corporate tax services, bookkeeping, and business consulting.',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-169641357599?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    reviews: [],
    viewCount: 320,
    verified: true,
    addedBy: 'admin'
  },

  // --- QUEBEC ---
  {
    id: 'qc-r1',
    name: 'Restaurant Sultan',
    category: CategoryType.FOOD_DRINK,
    address: '3450 Rue Ontario E, Montreal, QC H1W 1P7',
    phone: '(514) 525-3565',
    description: 'Authentic Turkish and Mediterranean cuisine in the heart of Montreal.',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    reviews: [],
    viewCount: 680,
    verified: true,
    addedBy: 'admin',
    region: 'QC',
  },
  {
    id: 'qc-r2',
    name: 'Istanbul Bakery Montreal',
    category: CategoryType.WHOLESALE,
    address: '1862 Rue Sainte-Catherine O, Montreal, QC H3H 1M4',
    phone: '(514) 935-7474',
    description: 'Fresh Turkish breads, pastries, and imported grocery items.',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    reviews: [],
    viewCount: 520,
    verified: true,
    addedBy: 'admin',
    region: 'QC',
  },
  {
    id: 'qc-h1',
    name: 'Dr. Emre Kaya - Family Medicine',
    category: CategoryType.HEALTH,
    address: '1255 Rue Guy, Montreal, QC H3H 2L3',
    phone: '(514) 555-0188',
    description: 'Bilingual family physician serving the Turkish community in Montreal.',
    imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71f1e59816?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviews: [],
    viewCount: 410,
    verified: true,
    addedBy: 'admin',
    region: 'QC',
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    title: 'Looking for Waitstaff',
    category: NotificationCategory.JOB_HIRING,
    description: 'Busy Turkish cafe in Toronto needs experienced waitstaff. Must speak Turkish and English.',
    contactInfo: 'hr@turkishcafe.ca',
    date: '2023-11-20',
    createdAt: Date.now() - 100000,
    userId: 'u1',
    approved: true
  },
  {
    id: 'n2',
    title: '2BR Apartment for Rent in Toronto',
    category: NotificationCategory.RENTAL,
    description: 'Clean, spacious 2BR near Metro. $1800/month. Perfect for new immigrants.',
    price: '$1800',
    contactInfo: '416-555-0123',
    date: '2023-11-21',
    createdAt: Date.now() - 50000,
    userId: 'u2',
    approved: true
  },
  {
    id: 'n-qc1',
    title: '2BR Apartment for Rent in Montreal',
    category: NotificationCategory.RENTAL,
    description: 'Bright 2BR near Metro Jean-Talon. $1650/month. Turkish landlord.',
    price: '$1650',
    contactInfo: '514-555-0199',
    location: 'Montreal, QC',
    date: '2024-01-15',
    createdAt: Date.now() - 40000,
    userId: 'u3',
    approved: true,
    region: 'QC',
  },
  {
    id: 'n-qc2',
    title: 'Turkish Teacher Wanted',
    category: NotificationCategory.JOB_HIRING,
    description: 'Weekend Turkish language classes in Laval. Experience preferred.',
    contactInfo: 'info@turkishschool.ca',
    location: 'Laval, QC',
    date: '2024-02-01',
    createdAt: Date.now() - 30000,
    userId: 'u4',
    approved: true,
    region: 'QC',
  },
];

export const INITIAL_EVENTS: Event[] = [
  {
    id: 'e1',
    title: 'Toronto Turkish Festival',
    date: '2024-07-15',
    location: 'Nathan Phillips Square, Toronto',
    description: 'Join us for a weekend of Turkish food, music, and dance in the heart of Toronto.',
    imageUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=800&q=80',
    organizer: 'Turkish Culture Society',
    approved: true
  },
  {
    id: 'e2',
    title: 'Business Networking Night',
    date: '2024-12-05',
    location: 'Downtown Toronto',
    description: 'An evening for Turkish entrepreneurs in GTA to connect and collaborate.',
    imageUrl: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=800&q=80',
    organizer: 'Turkish Canadian Chamber of Commerce',
    approved: true
  },
  {
    id: 'e3',
    title: 'Turkish Movie Night',
    date: '2024-11-15',
    location: 'North York Central Library',
    description: 'Come watch a classic Turkish film with the community. Popcorn and tea will be provided.',
    imageUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=800&q=80',
    organizer: 'Turkish Arts Center',
    approved: true
  },
  {
    id: 'e4',
    title: 'Children\'s Day Celebration',
    date: '2025-04-23',
    location: 'High Park, Toronto',
    description: 'Celebrating International Children\'s Day with games, music, and workshops for kids.',
    imageUrl: 'https://images.unsplash.com/photo-1472162072942-cd5147eb3902?auto=format&fit=crop&w=800&q=80',
    organizer: 'Turkish Community Federation',
    approved: true
  },
  {
    id: 'e5',
    title: 'Turkish Breakfast Meetup',
    date: '2024-10-20',
    location: 'Mississauga Lakeside Park',
    description: 'A casual morning gathering for a traditional Turkish breakfast by the lake.',
    imageUrl: 'https://images.unsplash.com/photo-1598514538064-f7a1ec85140e?auto=format&fit=crop&w=800&q=80',
    organizer: 'Peel Turkish Network',
    approved: true
  },
  {
    id: 'e6',
    title: 'Turkish Language Workshop',
    date: '2024-11-30',
    location: 'University of Guelph',
    description: 'A beginner-friendly workshop for those wanting to learn or improve their Turkish language skills.',
    imageUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=800&q=80',
    organizer: 'Guelph Turkish Student Association',
    approved: true
  },
  {
    id: 'e7',
    title: 'Youth Soccer Tournament',
    date: '2025-06-12',
    location: 'L\'Amoreaux Sports Complex, Scarborough',
    description: 'Community soccer tournament for youth ages 12-18. Medals and trophies for winners!',
    imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=800&q=80',
    organizer: 'Scarborough Turkish Sports Club',
    approved: true
  },
  {
    id: 'e8',
    title: 'Turkish Folk Dance Class',
    date: '2024-10-25',
    location: 'Vaughan Community Centre',
    description: 'Learn the basics of traditional Turkish folk dances. All levels welcome.',
    imageUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=800&q=80',
    organizer: 'Vaughan Turkish Arts Heritage',
    approved: true
  },
  {
    id: 'e9',
    title: 'Newcomer Orientation Seminar',
    date: '2024-11-05',
    location: 'Online via Zoom',
    description: 'Everything you need to know about life in Ontario: Housing, healthcare, and employment.',
    imageUrl: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&w=800&q=80',
    organizer: 'Turkish Canadian Support Services',
    approved: true
  },
  {
    id: 'e-qc1',
    title: 'Montreal Turkish Festival',
    date: '2024-08-10',
    location: 'Parc Jean-Drapeau, Montreal, QC',
    description: 'A weekend celebration of Turkish food, music, and culture on the island.',
    imageUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=800&q=80',
    organizer: 'Montreal Turkish Cultural Association',
    approved: true,
    region: 'QC',
  },
  {
    id: 'e-qc2',
    title: 'Quebec City Turkish Breakfast',
    date: '2024-09-14',
    location: 'Plains of Abraham, Quebec City, QC',
    description: 'Community breakfast meetup with traditional Turkish dishes and networking.',
    imageUrl: 'https://images.unsplash.com/photo-1598514538064-f7a1ec85140e?auto=format&fit=crop&w=800&q=80',
    organizer: 'Quebec City Turkish Network',
    approved: true,
    region: 'QC',
  },
];

export const INITIAL_TRAVELER_RECOMMENDATIONS: TravelerRecommendation[] = [
  {
    id: 'tr1',
    title: 'The Stunning Niagara Falls',
    userName: 'Emre Can',
    description: 'Breathtaking views, especially during sunset. A must-visit for everyone in Ontario.',
    media: [{ url: 'https://images.unsplash.com/photo-1516738901171-8eb4fc13bd20?auto=format&fit=crop&w=800&q=80', type: 'image' }],
    location: 'Niagara Falls, ON',
    date: '2024-05-10',
    approved: true
  },
  {
    id: 'tr2',
    title: 'Old Quebec City Charm',
    userName: 'Ayşe Yılmaz',
    description: 'Felt like I was in Europe! The cobblestone streets and historical architecture are magical.',
    media: [{ url: 'https://images.unsplash.com/photo-1598282361091-a1d227419139?auto=format&fit=crop&w=800&q=80', type: 'image' }],
    location: 'Quebec City, QC',
    date: '2024-03-22',
    approved: true
  }
];

export const INITIAL_BANNERS: BannerAd[] = [
  {
    id: 'b1',
    title: 'Turkish Airlines - Special Offers',
    url: 'https://images.unsplash.com/photo-1436491865332-7a61a109c0f3?auto=format&fit=crop&w=1200&q=80',
    type: 'image',
    link: 'https://turkishairlines.com',
    active: true
  },
  {
    id: 'b2',
    title: 'Istanbul Market - Fresh Daily',
    url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=80',
    type: 'image',
    link: '#',
    active: true
  },
  {
    id: 'b3',
    title: 'Real Estate Opportunities 2024',
    url: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1200&q=80',
    type: 'image',
    link: '#',
    active: true
  }
];

export const INITIAL_FLYERS: Flyer[] = [
  {
    id: 'f1',
    titleTr: "Süpermarket & Gıda Fırsatları",
    titleEn: "Supermarket & Turkish Grocery Deals",
    badgeTr: "HAFTALIK AKTÜEL",
    badgeEn: "WEEKLY DEALS",
    savings: "35%",
    items: [
      { nameTr: "Çaykur Rize Turist Çayı (1kg)", nameEn: "Caykur Black Rize Tea (1kg)", oldPrice: "$18.99", newPrice: "$12.99" },
      { nameTr: "Sera Siyah Zeytin L-Boy (900g)", nameEn: "Sera Black Olives L-Size (900g)", oldPrice: "$14.50", newPrice: "$9.99" },
      { nameTr: "Tadım Bol Tuzlu Ayçekirdeği", nameEn: "Tadim Salted Sunflower Seeds", oldPrice: "$4.99", newPrice: "$3.49" }
    ],
    themeColor: "bg-red-600",
    badgeColor: "bg-yellow-400 text-red-950",
    dateRangeTr: "25 May - 31 May",
    dateRangeEn: "May 25 - May 31",
    images: [
      "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&q=80&w=600"
    ],
    createdAt: 1716624000
  },
  {
    id: 'f2',
    titleTr: "Ev, Tekstil & Mutfak Kampanyası",
    titleEn: "Home, Textile & Kitchen Specials",
    badgeTr: "BÜYÜK FIRSAT",
    badgeEn: "HOT OFFER",
    savings: "40%",
    items: [
      { nameTr: "Paşabahçe İnce Belli Çay Seti", nameEn: "Pasabahce 12pc Tea Glass Set", oldPrice: "$29.99", newPrice: "$17.99" },
      { nameTr: "Saray Halı Anadolu Desen Yolluk", nameEn: "Anatolian Traditional Runner Rug", oldPrice: "$89.00", newPrice: "$54.00" },
      { nameTr: "Arzum Türk Kahvesi Makinesi", nameEn: "Arzum Turkish Coffee Maker", oldPrice: "$149.00", newPrice: "$99.00" }
    ],
    themeColor: "bg-amber-500",
    badgeColor: "bg-red-600 text-white",
    dateRangeTr: "25 May - 05 Haz",
    dateRangeEn: "May 25 - Jun 05",
    images: [
      "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&q=80&w=600"
    ],
    createdAt: 1716624001
  },
  {
    id: 'f3',
    titleTr: "Yerel Esnaf & Hizmet Flyer'ı",
    titleEn: "Local Services & Business Booklet",
    badgeTr: "İŞ BİRLİĞİ",
    badgeEn: "PARTNERSHIP",
    savings: "25%",
    items: [
      { nameTr: "Erkek Saç Kesimi & Sakal (Berber)", nameEn: "Men's Barber Haircut & Shave", oldPrice: "$45.00", newPrice: "$30.00" },
      { nameTr: "Havaalanı Özel VIP Transfer", nameEn: "Toronto Airport VIP Shuttle", oldPrice: "$120.00", newPrice: "$95.00" },
      { nameTr: "Göçmenlik Danışmanlık Seansı", nameEn: "Immigration Consulting Session", oldPrice: "$150.00", newPrice: "$110.00" }
    ],
    themeColor: "bg-emerald-600",
    badgeColor: "bg-yellow-300 text-emerald-950",
    dateRangeTr: "Özel Tarife",
    dateRangeEn: "Special Rates",
    images: [
      "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1585747860715-2da37e73522b?auto=format&fit=crop&q=80&w=600"
    ],
    createdAt: 1716624002
  }
];

export const INITIAL_PLACES = [
  { 
    id: 'p1',
    name: 'CN Tower', 
    province: 'Toronto, ON', 
    img: 'https://images.unsplash.com/photo-1551322019-335606d2003c?auto=format&fit=crop&w=400&q=80',
    address: '290 Bremner Blvd, Toronto, ON M5V 3L9',
    howToGet: 'Take the TTC to Union Station, follow signs for SkyWalk.',
    howToGetTr: 'TTC ile Union Station durağına gelin, SkyWalk tabelalarını takip edin.',
    tips: 'Book ahead! Avoid weekends for shorter lines. Bring a camera.',
    tipsTr: 'Önceden rezervasyon yapın! Hafta sonlarından kaçının. Kamera getirmeyi unutmayın.',
    price: 'Starting from $45',
    priceTr: '45$\'dan başlayan fiyatlarla',
    parking: 'Paid underground parking available nearby.',
    parkingTr: 'Yakınlarda ücretli yer altı otoparkı mevcut.',
    category: PlaceCategory.CITY,
  },
  { 
    id: 'p2',
    name: 'Niagara Falls', 
    province: 'Niagara, ON', 
    img: 'https://images.unsplash.com/photo-1516738901171-8eb4fc13bd20?auto=format&fit=crop&w=400&q=80',
    address: 'Niagara Falls, ON L2G 3Y9',
    howToGet: 'GO Train/Bus from Union Station or a 1.5-hour drive.',
    howToGetTr: 'Union Station\'dan GO Treni/Otobüsü veya 1.5 saatlik sürüş mesafesi.',
    tips: 'Bring a raincoat or waterproof poncho. Night lighting is beautiful.',
    tipsTr: 'Yağmurluk veya su geçirmez panço getirin. Gece ışıklandırması muhteşemdir.',
    price: 'Viewing is free, attractions cost extra',
    priceTr: 'İzlemek ücretsiz, etkinlikler ücretlidir',
    parking: 'Expensive lots near the falls. Cheaper lots further away.',
    parkingTr: 'Şelale yakınındaki otoparklar pahalıdır. Uzaklarda daha ucuz yerler var.',
    category: PlaceCategory.NATURE,
  },
  { 
    id: 'p3',
    name: 'Distillery District', 
    province: 'Toronto, ON', 
    img: 'https://images.unsplash.com/photo-1549247413-4315f606a4bc?auto=format&fit=crop&w=400&q=80',
    address: '55 Mill St, Toronto, ON M5A 3C4',
    howToGet: 'TTC Streetcar 504 King east to Parliament.',
    howToGetTr: 'Doğu yönüne giden TTC King 504 tramvayı ile Parliament durağı.',
    tips: 'Great for photography. Many galleries and boutiques.',
    tipsTr: 'Fotoğrafçılık için harika. Birçok galeri ve butik bulunuyor.',
    price: 'Free entry to district',
    priceTr: 'Giriş ücretsiz',
    parking: 'Paid street parking and lots available nearby.',
    parkingTr: 'Yakınlarda ücretli yol üstü park yerleri ve otoparklar mevcut.',
    category: PlaceCategory.CULTURE,
  },
  { 
    id: 'p4',
    name: 'Casa Loma', 
    province: 'Toronto, ON', 
    img: 'https://images.unsplash.com/photo-1579224422204-749e75558102?auto=format&fit=crop&w=400&q=80',
    address: '1 Austin Terrace, Toronto, ON M5R 1X8',
    howToGet: 'Short walk from Dupont Subway Station.',
    howToGetTr: 'Dupont Metro durağından kısa bir yürüyüş mesafesinde.',
    tips: 'Explore the tunnels and secret passages.',
    tipsTr: 'Tünelleri ve gizli geçitleri keşfedin.',
    price: 'Around $30',
    priceTr: 'Yaklaşık 30$',
    parking: 'On-site paid parking available.',
    parkingTr: 'Alan içinde ücretli otopark mevcut.',
    category: PlaceCategory.HERITAGE,
  },
  { 
    id: 'p5',
    name: 'Toronto Islands', 
    province: 'Toronto, ON', 
    img: 'https://images.unsplash.com/photo-1510253401511-370c97800c0f?auto=format&fit=crop&w=400&q=80',
    address: 'Jack Layton Ferry Terminal, Toronto, ON',
    howToGet: 'Ferry from Jack Layton Terminal at the foot of Bay St.',
    howToGetTr: 'Bay St. sonundaki Jack Layton Terminali\'nden feribot ile.',
    tips: 'Great skyline views. Rent a bike on the island.',
    tipsTr: 'Harika şehir silüeti manzarası. Adada bir bisiklet kiralayın.',
    price: 'Ferry ticket: ~$9 round trip',
    priceTr: 'Feribot bileti: ~9$ gidiş-dönüş',
    parking: 'No cars on island. Park near harborfront.',
    parkingTr: 'Adada araba yasak. Harborfront yakınlarına park edin.',
    category: PlaceCategory.FAMILY,
  },
  { 
    id: 'p6',
    name: 'Royal Ontario Museum', 
    province: 'Toronto, ON', 
    img: 'https://images.unsplash.com/photo-1566438480900-0609be27a4be?auto=format&fit=crop&w=400&q=80',
    address: '100 Queens Park, Toronto, ON M5S 2C6',
    howToGet: 'Saint George or Museum Subway Stations.',
    howToGetTr: 'Saint George veya Museum Metro durakları.',
    tips: 'Check for free admission nights (third Tuesday).',
    tipsTr: 'Ücretsiz giriş gecelerini takip edin (üçüncü Salı).',
    price: 'Around $23',
    priceTr: 'Yaklaşık 23$',
    parking: 'Nearby paid lots and street parking.',
    parkingTr: 'Yakınlarda ücretli otoparklar ve yol üstü park yerleri.',
    category: PlaceCategory.CULTURE,
  },
  {
    id: 'p-qc1',
    name: 'Old Montreal',
    province: 'Montreal, QC',
    img: 'https://images.unsplash.com/photo-1598282361091-a1d227419139?auto=format&fit=crop&w=400&q=80',
    address: 'Vieux-Montréal, Montreal, QC',
    howToGet: 'Metro to Place-d\'Armes or Champ-de-Mars station.',
    howToGetTr: 'Place-d\'Armes veya Champ-de-Mars metro durağına gidin.',
    tips: 'Best explored on foot. Cobblestone streets and historic architecture.',
    tipsTr: 'Yürüyerek keşfedin. Arnavut kaldırımlı sokaklar ve tarihi mimari.',
    price: 'Free to walk around',
    priceTr: 'Gezmek ücretsiz',
    parking: 'Limited street parking. Use nearby lots.',
    parkingTr: 'Sınırlı sokak parkı. Yakın otoparkları kullanın.',
    category: PlaceCategory.HERITAGE,
    region: 'QC',
  },
  {
    id: 'p-qc2',
    name: 'Mont-Royal Park',
    province: 'Montreal, QC',
    img: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=400&q=80',
    address: '1260 Chemin Remembrance, Montreal, QC H3H 1A2',
    howToGet: 'Bus 11 from Metro Mont-Royal or hike from the park entrance.',
    howToGetTr: 'Mont-Royal metrodan 11 numaralı otobüs veya park girişinden yürüyüş.',
    tips: 'Best skyline views at the Kondiaronk Belvedere lookout.',
    tipsTr: 'En iyi şehir manzarası Kondiaronk Belvedere seyir noktasında.',
    price: 'Free entry',
    priceTr: 'Giriş ücretsiz',
    parking: 'Paid lots near Beaver Lake and Smith House.',
    parkingTr: 'Beaver Lake ve Smith House yakınında ücretli otopark.',
    category: PlaceCategory.NATURE,
    region: 'QC',
  },
  {
    id: 'p-qc3',
    name: 'Château Frontenac Area',
    province: 'Quebec City, QC',
    img: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=400&q=80',
    address: '1 Rue des Carrières, Quebec City, QC G1R 4P5',
    howToGet: 'Walk from Quebec City Old Town or take a local bus.',
    howToGetTr: 'Quebec City Eski Şehir\'den yürüyün veya yerel otobüs kullanın.',
    tips: 'Iconic landmark with stunning views of the St. Lawrence River.',
    tipsTr: 'St. Lawrence Nehri\'ne muhteşem manzaralı ikonik simge yapı.',
    price: 'Free to view from outside',
    priceTr: 'Dışarıdan izlemek ücretsiz',
    parking: 'Underground parking at Dufferin Terrace.',
    parkingTr: 'Dufferin Terrace altında yer altı otoparkı.',
    category: PlaceCategory.HERITAGE,
    region: 'QC',
  },
];

